version: "3.0"

services:
  timescaleDb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaleDb
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exchange
    # volumes:
      # - timescale-data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  timescale-data: